// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: catalog/v1/changeset.proto

package catalog

import (
	_ "github.com/open-cloud-initiative/marketplace/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChangeSetStatus int32

const (
	// ChangeSetStatusUnspecified is the default value.
	ChangeSetStatus_CHANGE_SET_STATUS_UNSPECIFIED ChangeSetStatus = 0
	// ChangeSet is pending.
	ChangeSetStatus_CHANGE_SET_STATUS_PENDING ChangeSetStatus = 1
	// ChangeSet is applied.
	ChangeSetStatus_CHANGE_SET_STATUS_APPLIED ChangeSetStatus = 2
	// ChangeSet is failed.
	ChangeSetStatus_CHANGE_SET_STATUS_FAILED ChangeSetStatus = 3
)

// Enum value maps for ChangeSetStatus.
var (
	ChangeSetStatus_name = map[int32]string{
		0: "CHANGE_SET_STATUS_UNSPECIFIED",
		1: "CHANGE_SET_STATUS_PENDING",
		2: "CHANGE_SET_STATUS_APPLIED",
		3: "CHANGE_SET_STATUS_FAILED",
	}
	ChangeSetStatus_value = map[string]int32{
		"CHANGE_SET_STATUS_UNSPECIFIED": 0,
		"CHANGE_SET_STATUS_PENDING":     1,
		"CHANGE_SET_STATUS_APPLIED":     2,
		"CHANGE_SET_STATUS_FAILED":      3,
	}
)

func (x ChangeSetStatus) Enum() *ChangeSetStatus {
	p := new(ChangeSetStatus)
	*p = x
	return p
}

func (x ChangeSetStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeSetStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_catalog_v1_changeset_proto_enumTypes[0].Descriptor()
}

func (ChangeSetStatus) Type() protoreflect.EnumType {
	return &file_catalog_v1_changeset_proto_enumTypes[0]
}

func (x ChangeSetStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeSetStatus.Descriptor instead.
func (ChangeSetStatus) EnumDescriptor() ([]byte, []int) {
	return file_catalog_v1_changeset_proto_rawDescGZIP(), []int{0}
}

// Change represents a single change to be applied to a catalog.
type Change struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name of the change. Must be unique within the ChangeSet.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the change.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Change) Reset() {
	*x = Change{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catalog_v1_changeset_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Change) ProtoMessage() {}

func (x *Change) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_changeset_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Change.ProtoReflect.Descriptor instead.
func (*Change) Descriptor() ([]byte, []int) {
	return file_catalog_v1_changeset_proto_rawDescGZIP(), []int{0}
}

func (x *Change) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Change) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// ChangeSet represents a set of changes to be applied to a catalog.
type ChangeSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Catalog identifier.
	Catalog *Catalog `protobuf:"bytes,1,opt,name=catalog,proto3" json:"catalog,omitempty"`
	// Name of the ChangeSet. Must be unique within the catalog.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Changes in the ChangeSet.
	Changes []*Change `protobuf:"bytes,3,rep,name=changes,proto3" json:"changes,omitempty"`
}

func (x *ChangeSet) Reset() {
	*x = ChangeSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catalog_v1_changeset_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeSet) ProtoMessage() {}

func (x *ChangeSet) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_changeset_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeSet.ProtoReflect.Descriptor instead.
func (*ChangeSet) Descriptor() ([]byte, []int) {
	return file_catalog_v1_changeset_proto_rawDescGZIP(), []int{1}
}

func (x *ChangeSet) GetCatalog() *Catalog {
	if x != nil {
		return x.Catalog
	}
	return nil
}

func (x *ChangeSet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChangeSet) GetChanges() []*Change {
	if x != nil {
		return x.Changes
	}
	return nil
}

var File_catalog_v1_changeset_proto protoreflect.FileDescriptor

var file_catalog_v1_changeset_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x73, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x6f, 0x63,
	0x69, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x63, 0x61,
	0x74, 0x61, 0x6c, 0x6f, 0x67, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x63, 0x61, 0x74,
	0x61, 0x6c, 0x6f, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x06, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x9c, 0x01, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x53, 0x65, 0x74, 0x12, 0x3d, 0x0a, 0x07, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6f, 0x63, 0x69, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65,
	0x74, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x52, 0x07, 0x63, 0x61, 0x74, 0x61, 0x6c,
	0x6f, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3c, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6f, 0x63, 0x69, 0x2e, 0x6d, 0x61,
	0x72, 0x6b, 0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f,
	0x67, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x07, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x73, 0x2a, 0x90, 0x01, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53,
	0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x21, 0x0a, 0x1d, 0x43, 0x48, 0x41, 0x4e,
	0x47, 0x45, 0x5f, 0x53, 0x45, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1d, 0x0a, 0x19, 0x43,
	0x48, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x53, 0x45, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x1d, 0x0a, 0x19, 0x43, 0x48,
	0x41, 0x4e, 0x47, 0x45, 0x5f, 0x53, 0x45, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x41, 0x50, 0x50, 0x4c, 0x49, 0x45, 0x44, 0x10, 0x02, 0x12, 0x1c, 0x0a, 0x18, 0x43, 0x48, 0x41,
	0x4e, 0x47, 0x45, 0x5f, 0x53, 0x45, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x46,
	0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x42, 0x47, 0x5a, 0x45, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x2d, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x2d, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x69, 0x76, 0x65, 0x2f, 0x6d, 0x61, 0x72, 0x6b,
	0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61,
	0x74, 0x61, 0x6c, 0x6f, 0x67, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_catalog_v1_changeset_proto_rawDescOnce sync.Once
	file_catalog_v1_changeset_proto_rawDescData = file_catalog_v1_changeset_proto_rawDesc
)

func file_catalog_v1_changeset_proto_rawDescGZIP() []byte {
	file_catalog_v1_changeset_proto_rawDescOnce.Do(func() {
		file_catalog_v1_changeset_proto_rawDescData = protoimpl.X.CompressGZIP(file_catalog_v1_changeset_proto_rawDescData)
	})
	return file_catalog_v1_changeset_proto_rawDescData
}

var file_catalog_v1_changeset_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_catalog_v1_changeset_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_catalog_v1_changeset_proto_goTypes = []interface{}{
	(ChangeSetStatus)(0), // 0: oci.marketplace.catalog.v1.ChangeSetStatus
	(*Change)(nil),       // 1: oci.marketplace.catalog.v1.Change
	(*ChangeSet)(nil),    // 2: oci.marketplace.catalog.v1.ChangeSet
	(*Catalog)(nil),      // 3: oci.marketplace.catalog.v1.Catalog
}
var file_catalog_v1_changeset_proto_depIdxs = []int32{
	3, // 0: oci.marketplace.catalog.v1.ChangeSet.catalog:type_name -> oci.marketplace.catalog.v1.Catalog
	1, // 1: oci.marketplace.catalog.v1.ChangeSet.changes:type_name -> oci.marketplace.catalog.v1.Change
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_catalog_v1_changeset_proto_init() }
func file_catalog_v1_changeset_proto_init() {
	if File_catalog_v1_changeset_proto != nil {
		return
	}
	file_catalog_v1_catalog_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_catalog_v1_changeset_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Change); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catalog_v1_changeset_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_catalog_v1_changeset_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_v1_changeset_proto_goTypes,
		DependencyIndexes: file_catalog_v1_changeset_proto_depIdxs,
		EnumInfos:         file_catalog_v1_changeset_proto_enumTypes,
		MessageInfos:      file_catalog_v1_changeset_proto_msgTypes,
	}.Build()
	File_catalog_v1_changeset_proto = out.File
	file_catalog_v1_changeset_proto_rawDesc = nil
	file_catalog_v1_changeset_proto_goTypes = nil
	file_catalog_v1_changeset_proto_depIdxs = nil
}
